name: ilenia-rag-frontend

services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: ilenia-db-prod
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD_ROOT:-password}
      MYSQL_DATABASE: ${DB_NAME:-ilenia-rag-frontend}
      MYSQL_USER: ${DB_USER:-user}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ilenia_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ilenia-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Backend (Server)
  server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    container_name: ilenia-server-prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    #command: sh -c "npx run db:migrate && npx start"
    networks:
      - ilenia-net

  # Frontend (Web)
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: ilenia-web-prod
    restart: unless-stopped
    depends_on:
      - server
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    networks:
      - ilenia-net

volumes:
  ilenia_db_data:

networks:
  ilenia-net:
    driver: bridge